// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

// Fallback values keep the app booting even when build-time env vars are missing.
// These are public client credentials (anon key, protected by RLS) and are already
// shipped in the browser bundle, so it is safe to inline them here. Env vars still
// win when provided.
const SUPABASE_URL =
  import.meta.env.VITE_SUPABASE_URL ?? "https://ihkbxdayhdewqzezdrfl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY =
  import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY ??
  "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imloa2J4ZGF5aGRld3F6ZXpkcmZsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjkxMTMyMjksImV4cCI6MjA4NDY4OTIyOX0.c57QIqCeeLVxthb3gHy3XxkpDovNXGFztZN4xlGIOck";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});