name: Deploy

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 20

      - run: npm install
      - run: npm run build

      - name: Upload via SFTP
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ip-173-255-192-155.cloudezapp.io
          port: 22122
          username: customforlife3
          password: ${{ secrets.DEPLOY_PASSWORD }}
          source: dist/*
          target: /home/customforlife3/customforlife.com.br/www/dist/

      - name: Copy to www
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ip-173-255-192-155.cloudezapp.io
          port: 22122
          username: customforlife3
          password: ${{ secrets.DEPLOY_PASSWORD }}
          script: |
            rm -rf ~/customforlife.com.br/www/assets
            rm -f ~/customforlife.com.br/www/index.html
            cp -r ~/customforlife.com.br/www/dist/* ~/customforlife.com.br/www/
